src/Tracktor/Tracktor.Web/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tracktor.Business;
using Tracktor.Domain;
using Tracktor.Web.ViewModels.Place;

namespace Tracktor.Web.Controllers
{
    public class PlaceController : Controller
    {

        public ActionResult AddPlace()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPlace(AddPlaceVM vm)
        {
            var pe = new PlaceEntity
            {
                Location = new GeoCoordinate
                {
                    Latitude = double.Parse(vm.Lat, CultureInfo.InvariantCulture),
                    Longitude = double.Parse(vm.Lng, CultureInfo.InvariantCulture),
                },
                Name = vm.Name,
            };
            var placeService = ServiceFactory.getPlaceServices().Add(pe);

            return RedirectToAction("AddInfo", "Event");
        }

        public ActionResult AddPlaceToList()
        {
            var vm = new AddPlaceToListVM { Places = ServiceFactory.getPlaceServices().GetAll(), };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddPlaceToList(AddPlaceToListVM vm)
        {
            var userId = (Session["user"] as UserEntity).Id;
            if (vm.PlaceId != -1)
            {
                var userService = ServiceFactory.getUserServices();
                if (vm.SponsoredPlace.Selected) { userService.AddSponsorPlace(userId, vm.PlaceId); }
                if (vm.FavouritePlace.Selected) { userService.AddFavouritePlace(userId, vm.PlaceId); }
            }

            return RedirectToAction("Search", "Event");
        }
    }
}

src/Tracktor/Tracktor.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tracktor.Business;
using Tracktor.Domain;
using Tracktor.Web.ViewModels.User;

namespace Tracktor.Web.Controllers
{
    public class UserController : Controller
    {
        //GET: LogIn
        public ActionResult LogIn()
        {
            return View(new LogInVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(LogInVM vm)
        {
            var userService = ServiceFactory.getUserServices();
            var le = new LoginEntity { Username = vm.Username, Password = vm.Password };
            try
            {
                var userId = userService.Login(le);
                var user = userService.Get(userId);
                Session["user"] = user;
                return RedirectToAction("Search", "Event");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(vm);
            }
        }

        //GET: LogOut
        public ActionResult LogOut()
        {
            Session["user"] = null;
            return RedirectToAction(nameof(LogIn));
        }
    }
}

src/Tracktor/Tracktor.Web/Views/Shared/_Layout.cshtml
@using Tracktor.Domain

@{
    var user = (UserEntity)Session["user"];
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tracktor - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (user == null)
                {
                    @Html.ActionLink("Tracktor", "LogIn", "User", new { area = "" }, new { @class = "navbar-brand" })
                }
                else
                {
                    @Html.ActionLink("Tracktor", "Search", "Event", new { area = "" }, new { @class = "navbar-brand" })
                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (user == null)
                    {
                        <li>@Html.ActionLink("Log in", "LogIn", "User")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Search", "Event")</li>
                        <li>@Html.ActionLink("Add info", "AddInfo", "Event")</li>
                        <li>@Html.ActionLink("Add place to list", "AddPlaceToList", "Place")</li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (user != null)
                    {
                        <li><p class="navbar-text">@user.FullName</p></li>
                        <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tracktor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>